### ISSUE TITLE
해당 솔루션에 대한 반응 및 피드백

### ISSUE THREAD

**Issue by nahyunsama** [junhoyeo/standard-is#2]
이슈를 열어보는게 처음이라 다소 어색할 수 있지만 양해해주시면 감사합니다.
먼저 레포에 정보 공유해주신 것을 잘 보았으며, 주변에 반응을 물어보았고, 그동안의 경험을 덧붙여 이슈를 열어봅니다.
1. 선페에 nohello.net (https://nohello.net/en/) 을 덧붙이면 좋을 것 같습니다.
2. 계기에 일상에서 있었던 신기한 일이나 재밌는 일을 이야기 한다 항목이 추가되면 좋을 것 같습니다.
3. 계기에 적당한 구실로 오프라인 약속을 잡는다 항목이 추가되면 좋을 것 같습니다(EX 내가 아는 맛있는 000이 있는데 같이 먹으러 갈래? 등)
4. 스윗 항목에 상대가 이야기한 것을 잘 기억하고 배려해주기 항목을 추가해주시면 감사합니다.
5. 연락파트에 "연락하지 말라고 하면 당장은 하지 말고 일정 시간이 경과한 뒤 연락한다." 항목에 통상 일주일을 추가하면 좋을 것 같습니다.
6. 연락을 마감할때 파트에 '하지만 꼭 안정적인 handshake 통신 종료를 하지 않아도 괜찮으며, 인간이라는 특성 상 다음날 아침에 적당히 읽고 스루할 수도 있고, 이어 갈 수도 있으니 크게 괘념치 않아도 괜찮다' 를 잘 정리해서 추가해주시면 감사합니다.
7. 웃음 파트에 웃는 귀여운 이모티콘을 활용한다 항목을 추가하면 좋을 것 같습니다.
8. 고백에 어느 정도 상호 호감이 확인 되고, 그것이 안정 되었을 때 직접 만나서 직설적이고 존댓말로 한다 항목과 조건에 서로 편안하고 안정적이며, 어느 정도 상대 사고 로직에 대해 알고 있음 을 추가해주시면 감사합니다. 추천방법에 야밤 저녁이나 술을 먹고 집에 데려다주며도 추가해주시면 감사합니다.

문과 친구의 반응 : 그 뭔 오랑캐 같은 글인지 모르겠는데 그래 이런거라도 읽혀야지 사람 된다.

용기내어 공개 레포로 올려 고로시와 웃음 마다하지 않고 인간관계의 소통을 문서화에 힘써주신 junhoyeo님께 감사드립니다.

**Comment by junhoyeo** [comment]
와우 @nyahyun 님, 시간내서 이슈 남겨주신 것 정말 감사합니다. 제 인생에도 반영해볼게요!

적어주신 정보만으로도 이미 엄청나게 커다란 도움이 될 것 같은데요. 직접 PR을 올려주시는 건 어떠세요? 

> 웃는 귀여운 이모티콘

최근 MZ세대의 경우 `🥹` 이모지(*울음을 참는 얼굴*)를 활용하는 것으로 파악됩니다. 해당 내용도 함께 추가하겠습니다.

> 상대가 이야기한 것을 잘 기억하고 배려해주기

저도 [Memory](https://js.langchain.com/docs/modules/memory/)를 두려고 노력하는데 가끔 쿼리가 너무 어렵네요... 인덱싱을 주기적으로 해야겠습니다...
(사실 나름 자신있는 편)

👍👍 좋은 포인트입니다.

> 하지만 꼭 안정적인 handshake 통신 종료를 하지 않아도 괜찮으며, 인간이라는 특성 상 다음날 아침에 적당히 읽고 스루할 수도 있고, 이어 갈 수도 있으니 크게 괘념치 않아도 괜찮다

👍👍 그나저나 [`로컬 피씨에서 TCP 패킷을 받아 UDP 패킷으로 변경하여 송수신할 수 있는 모듈` 에 대한 특허](https://patents.google.com/patent/KR100748900B1/ko)가 있었네요. ㄷㄷ


> 문과 친구의 반응 : 그 뭔 오랑캐 같은 글인지 모르겠는데 그래 이런거라도 읽혀야지 사람 된다.

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

> 용기내어 공개 레포로 올려 고로시와 웃음 마다하지 않고 인간관계의 소통을 문서화에 힘써주신 junhoyeo님께 감사드립니다.

- 고등학교 입학했을 때 재미삼아 Gist에 올렸다가 작년에 오랜만에 보고 레포로 만들었었어요 ㅋㅋㅋ
- 왜인지 모르겠는데 오늘 아침부터 스타가 갑자기 연달아 박히네요😂 많은 분들께 웃음을 드린 것 같아 기쁩니다!

**Comment by nahyunsama** [comment]
답변 주셔서 감사합니다.
제가 GIT은 익숙치 않지만 까짓것 해보죠라는 마인드로 PR 해보도록 하겠습니다.

웃는 귀여운 이모티콘의 경우 피엥 뿐만 아니라 대충 인스턴스 메신저 고유의 이모티콘을 이야기 한 거였는데 크게 상관은 없을 것 같습니다.

뭐 대충 이렇게 GIT 사용법을 익히는 거겠죠 조만간 PR 해보도록 하겠습니다.
감사합니다!

**Comment by junhoyeo** [comment]
> 웃는 귀여운 이모티콘의 경우 피엥 뿐만 아니라 대충 인스턴스 메신저 고유의 이모티콘

오 매우 중요하죠! 저도 귀엽고 뽀짝한 것들을 매우 좋아하기 때문에 나중에 https://e.kakao.com 등 다양한 스토어에서 제 마음에 드는 임티들을 골라서 넣어보겠습니다.

> 제가 GIT은 익숙치 않지만 까짓것 해보죠라는 마인드로 PR 해보도록 하겠습니다.

크크 이렇게 또 한 분을 깃의 세계로 온보딩 시켜드렸군요. ✨ 하시다가 막히시거나 궁금하신 것 생기시면 언제든 연락 남겨주세요!
